/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'transactionStatus': MotiaStream<{ id: string; transactionId: string; type: 'payment' | 'transfer' | 'deposit' | 'withdrawal'; status: string; previousStatus?: string; amount?: number; currency?: string; provider?: string; updatedAt: string }>
  }

  interface Handlers {
    'RequestWithdrawV2': ApiRouteHandler<{ amount: number; currency?: string; from: string; payerMessage?: string; description?: string; provider?: 'MTN' | 'ORANGE' }, unknown, { topic: 'withdrawal.created'; data: never }>
    'ListWithdrawals': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetWithdrawal': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetWithdrawalStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateWithdrawal': ApiRouteHandler<{ withdrawId?: string; accountId: string; amount: number; currency: string; description?: string; provider: string; metadata?: unknown }, unknown, { topic: 'withdrawal.created'; data: never }>
    'WebhookStream': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TestWebhook': ApiRouteHandler<{ paymentId: string; status?: 'SUCCESSFUL' | 'FAILED'; provider?: string }, unknown, never>
    'RetryFailedWebhooksApi': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ReplayWebhookDelivery': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'webhook.delivery.replayed'; data: never }>
    'ProviderWebhook': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'webhook.mtn.received'; data: never } | { topic: 'webhook.orange.received'; data: never }>
    'OrangeWebhook': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'webhook.orange.received'; data: never }>
    'NotifyWebhook': ApiRouteHandler<{ event: 'payment.completed' | 'payment.failed' | 'payment.refunded' | 'payment.updated' | 'transfer.completed' | 'transfer.failed' | 'transfer.updated' | 'transfer.created' | 'deposit.completed' | 'deposit.failed' | 'deposit.updated' | 'deposit.created' | 'withdrawal.completed' | 'withdrawal.failed' | 'withdrawal.updated' | 'withdrawal.created' | 'preapproval.created' | 'preapproval.approved' | 'preapproval.rejected' | 'preapproval.expired' | 'preapproval.cancelled' | 'preapproval.failed'; paymentId?: string; transferId?: string; depositId?: string; withdrawalId?: string; preapprovalId?: string; timestamp: string; data?: Record<string, unknown> }, unknown, { topic: 'webhook.notification.queued'; data: never }>
    'MtnWebhook': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'webhook.mtn.received'; data: never } | { topic: 'payment.updated'; data: never } | { topic: 'transfer.updated'; data: never } | { topic: 'deposit.updated'; data: never } | { topic: 'withdrawal.updated'; data: never }>
    'ListWebhookDeliveries': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetWebhookStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetWebhookDelivery': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ConfigureWebhook': ApiRouteHandler<{ url: string; events?: Array<string>; secret?: string }, unknown, never>
    'ValidateAccount': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ListTransfers': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetTransfer': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetTransferStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAccountUserInfo': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAccountBalance': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateTransfer': ApiRouteHandler<{ transferId?: string; from: string; to: string; amount: number; currency: string; description?: string; provider: 'MTN' | 'ORANGE'; metadata?: unknown }, unknown, { topic: 'transfer.created'; data: never }>
    'GetCashTransferStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CashTransfer': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'cashtransfer.created'; data: never }>
    'ListPreApprovals': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetPreApproval': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetPreApprovalStatus': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'preapproval.updated'; data: never }>
    'GetApprovedPreApprovals': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreatePreApproval': ApiRouteHandler<{ preApprovalId?: string; payerPhone: string; payerCurrency?: string; payerMessage?: string; validityTime: number; provider?: 'MTN' | 'ORANGE'; metadata?: Record<string, unknown> }, unknown, { topic: 'preapproval.created'; data: never }>
    'CancelPreApproval': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'preapproval.cancelled'; data: never }>
    'SendPaymentNotification': ApiRouteHandler<{ message: string }, unknown, never>
    'RefundPayment': ApiRouteHandler<{ amount?: number; reason?: string }, unknown, { topic: 'payment.refunded'; data: never }>
    'ListPaymentRefunds': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ListPayments': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetPaymentStats': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetRefundStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetPayment': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetPaymentStatusV2': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateRefundV2': ApiRouteHandler<{ transactionId: string; amount?: number; reason?: string; provider?: 'MTN' | 'ORANGE' }, unknown, { topic: 'refund.created'; data: never }>
    'CreatePayment': ApiRouteHandler<{ from: string; to: string; amount: number; timestamp: string; id?: string; provider?: string; providerMode?: string; providerOptions?: unknown }, unknown, { topic: 'payment.created'; data: never }>
    'CreatePaymentV2': ApiRouteHandler<{ amount: number; currency?: string; from: string; description?: string; externalTransactionId?: string; customerReference?: string; serviceProviderUserName?: string; couponId?: string; productId?: string; productOfferingId?: string; receiverMessage?: string; senderNote?: string; maxNumberOfRetries?: number; includeSenderCharges?: boolean; provider?: 'MTN' | 'ORANGE' }, unknown, { topic: 'payment.created'; data: never }>
    'CancelPayment': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'payment.cancelled'; data: never }>
    'GetInvoiceStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateInvoice': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'invoice.created'; data: never }>
    'CancelInvoice': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'invoice.cancelled'; data: never }>
    'HealthReady': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ProcessWebhookReceived': EventHandler<never, never>
    'ProcessTransactionCreated': EventHandler<never, never>
    'ProcessRefundCreated': EventHandler<never, never>
    'ProcessPaymentCreated': EventHandler<never, never>
    'ProcessInvoiceCreated': EventHandler<never, never>
    'ProcessInvoiceCancelled': EventHandler<never, never>
    'ProcessCashTransferCreated': EventHandler<never, never>
    'ProcessBalanceUpdate': EventHandler<never, never>
    'ForwardMerchantWebhook': EventHandler<never, never>
    'AuditWebhookActivity': EventHandler<never, never>
    'AuditUserActivity': EventHandler<never, never>
    'AuditPreapprovalActivity': EventHandler<never, never>
    'AuditConsentActivity': EventHandler<never, never>
    'AuditAdminActivity': EventHandler<never, never>
    'GetDepositStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateDeposit': ApiRouteHandler<{ depositId?: string; accountId: string; amount: number; currency: string; description?: string; provider: 'MTN' | 'ORANGE'; metadata?: unknown }, unknown, { topic: 'deposit.created'; data: never }>
    'CreateDepositV2': ApiRouteHandler<{ amount: number; currency?: string; accountId: string; description?: string; provider?: 'MTN' | 'ORANGE' }, unknown, { topic: 'deposit.created'; data: never }>
    'SyncPendingTransactions': CronHandler<never>
    'RetryFailedWebhooks': CronHandler<never>
    'PollPendingTransfers': CronHandler<{ topic: 'transfer.updated'; data: never }>
    'PollPendingPayments': CronHandler<{ topic: 'payment.updated'; data: never }>
    'RevokeConsent': ApiRouteHandler<{ accessToken: string; provider?: string }, unknown, { topic: 'consent.revoked'; data: never }>
    'RefreshConsentToken': ApiRouteHandler<{ refreshToken: string; provider?: string }, unknown, never>
    'GetUserInfoFromToken': ApiRouteHandler<{ accessToken: string; provider?: string }, unknown, never>
    'GetConsentToken': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetBasicUserInfo': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateSubscriptionConsent': ApiRouteHandler<{ customerId: string; businessId: string; amount: number; frequency: 'monthly' | 'weekly' | 'daily'; provider?: string }, unknown, { topic: 'consent.subscription.created'; data: never }>
    'CreateConsent': ApiRouteHandler<{ customerId: string; scope: string; accessType: 'online' | 'offline'; consentValidIn?: number | string; businessId: string; description?: string; provider?: string; metadata?: unknown }, unknown, { topic: 'consent.created'; data: never }>
    'CreateBillPaymentConsent': ApiRouteHandler<{ customerId: string; businessId: string; maxAmount: number; provider?: string }, unknown, { topic: 'consent.bill-payment.created'; data: never }>
    'CreateAccountAccessConsent': ApiRouteHandler<{ customerId: string; businessId: string; provider?: string }, unknown, { topic: 'consent.account-access.created'; data: never }>
    'RefreshBalance': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'balance.refreshed'; data: never }>
    'GetWalletBalances': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetTransactionHistory': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetProviderBalances': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetProviderBalance': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetBalanceByCurrency': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAggregatedBalance': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthRevokeApiKey': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'apikey.revoked'; data: never }>
    'AuthRegister': ApiRouteHandler<{ email: string; username: string; password: string; businessName: string; phoneNumber?: string }, unknown, { topic: 'user.registered'; data: never }>
    'AuthLogin': ApiRouteHandler<{ email: string; password: string }, unknown, { topic: 'user.logged_in'; data: never }>
    'AuthListApiKeys': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthCreateApiKey': ApiRouteHandler<{ name: string; mode: 'sandbox' | 'live' }, unknown, { topic: 'apikey.created'; data: never }>
    'UpdateFeeStructure': ApiRouteHandler<{ name?: string; description?: string; percentage?: number; minFee?: number; maxFee?: number; fixedFee?: number; isDefault?: boolean; isActive?: boolean }, unknown, never>
    'ListFeeStructures': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetRevenueReport': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetMerchantFeeHistory': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetMerchantCurrentFee': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCurrentAdmin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateVolumeTier': ApiRouteHandler<{ name: string; minVolume: number; maxVolume?: number; percentage: number; minFee: number; maxFee: number }, unknown, never>
    'CreateFeeStructure': ApiRouteHandler<{ name: string; description?: string; percentage: number; minFee: number; maxFee: number; fixedFee?: number; isDefault?: boolean }, unknown, never>
    'CreateAdmin': ApiRouteHandler<{ email: string; password: string; firstName?: string; lastName?: string; businessName?: string; role: 'ADMIN' | 'SUPER_ADMIN' }, unknown, { topic: 'admin.created'; data: never }>
    'CalculateFee': ApiRouteHandler<{ amount: number; userId: string }, unknown, never>
    'AssignMerchantFee': ApiRouteHandler<{ userId: string; feeStructureId: string; customPercentage?: number; customMinFee?: number; customMaxFee?: number; notes?: string }, unknown, never>
    'AdminLogin': ApiRouteHandler<{ username?: string; email?: string; password: string }, unknown, { topic: 'admin.logged_in'; data: never }>
  }
    
}